# nome da pipeline
name: run basic tests

# em que momento sera executada
on:
  pull_request:
    branches: [main]

# o que vai ser feito nessa pipeline
jobs:
  cypress-run:
    runs-on: ubuntu-latest # maquina que será executada
    steps: # passo a passo para rodar os testes
      - name: Checkout/Clone do projeto # clone do projeto
        uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      - name: Run tests #execução e configuração do projeto
        uses: cypress-io/github-action@v5
        with:
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY  }}

      - name: Instalar dependencias do projeto
        run: npm install # executa no terminal

      # upload do relatorio do mocha
      - name: upload relatorio mocha
        uses: actions/upload-artifact@v3
        with:
          name: Relatorio
          path: cypress/results/assets