# nome da pipeline
name: run basic tests

# em que momento sera executada
on:
  pull_request:
    branches: [main]

# o que vai ser feito nessa pipeline
jobs:
  cypress-run:
    runs-on: ubuntu-latest # maquina que será executada
    steps: # passo a passo para rodar os testes
      - name: Checkout/Clone do projeto # clone do projeto
        uses: actions/checkout@v3

      - name: Run tests #execução e configuração do projeto
        uses: cypress-io/github-action@v5
        with:
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY  }}

      - name: Instalar dependencias do projeto
        run: npm install # executa no terminal